//! `SeaORM` Entity, @generated by sea-orm-codegen 1.0.1

pub use super::open_options::Entity as OpenOptions;
pub use super::packet::Entity as Packet;
pub use super::serial_port::Entity as SerialPort;
