/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppDrawer: typeof import('./components/AppDrawer.vue')['default']
    AppFooter: typeof import('./components/AppFooter.vue')['default']
    Button: typeof import('./components/ui/button/Button.vue')['default']
    MessageList: typeof import('./components/com/MessageList.vue')['default']
    MessageListItem: typeof import('./components/com/MessageListItem.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SerialMonitor: typeof import('./components/SerialMonitor.vue')['default']
    SerialPort: typeof import('./components/serial-port/SerialPort.vue')['default']
    SerialPorts: typeof import('./components/SerialPorts.vue')['default']
    Sidebar: typeof import('./components/ui/sidebar/Sidebar.vue')['default']
    SidebarContent: typeof import('./components/ui/sidebar/SidebarContent.vue')['default']
    SidebarFooter: typeof import('./components/ui/sidebar/SidebarFooter.vue')['default']
    SidebarGroup: typeof import('./components/ui/sidebar/SidebarGroup.vue')['default']
    SidebarGroupAction: typeof import('./components/ui/sidebar/SidebarGroupAction.vue')['default']
    SidebarGroupContent: typeof import('./components/ui/sidebar/SidebarGroupContent.vue')['default']
    SidebarGroupLabel: typeof import('./components/ui/sidebar/SidebarGroupLabel.vue')['default']
    SidebarHeader: typeof import('./components/ui/sidebar/SidebarHeader.vue')['default']
    SidebarInput: typeof import('./components/ui/sidebar/SidebarInput.vue')['default']
    SidebarInset: typeof import('./components/ui/sidebar/SidebarInset.vue')['default']
    SidebarMenu: typeof import('./components/ui/sidebar/SidebarMenu.vue')['default']
    SidebarMenuAction: typeof import('./components/ui/sidebar/SidebarMenuAction.vue')['default']
    SidebarMenuBadge: typeof import('./components/ui/sidebar/SidebarMenuBadge.vue')['default']
    SidebarMenuButton: typeof import('./components/ui/sidebar/SidebarMenuButton.vue')['default']
    SidebarMenuButtonChild: typeof import('./components/ui/sidebar/SidebarMenuButtonChild.vue')['default']
    SidebarMenuItem: typeof import('./components/ui/sidebar/SidebarMenuItem.vue')['default']
    SidebarMenuSkeleton: typeof import('./components/ui/sidebar/SidebarMenuSkeleton.vue')['default']
    SidebarMenuSub: typeof import('./components/ui/sidebar/SidebarMenuSub.vue')['default']
    SidebarMenuSubButton: typeof import('./components/ui/sidebar/SidebarMenuSubButton.vue')['default']
    SidebarMenuSubItem: typeof import('./components/ui/sidebar/SidebarMenuSubItem.vue')['default']
    SidebarProvider: typeof import('./components/ui/sidebar/SidebarProvider.vue')['default']
    SidebarRail: typeof import('./components/ui/sidebar/SidebarRail.vue')['default']
    SidebarSeparator: typeof import('./components/ui/sidebar/SidebarSeparator.vue')['default']
    SidebarTrigger: typeof import('./components/ui/sidebar/SidebarTrigger.vue')['default']
  }
}
